"""Rules to declare translate-c toolchains."""

load(
    "//zig/private/providers:zig_module_info.bzl",
    "ZigModuleInfo",
)

TranslateCToolchainInfo = provider(
    doc = "Information about how to invoke an external translate-c executable.",
    fields = {
        "executable": "File, The translate-c executable.",
        "files_to_run": "FilesToRunProvider, The translate-c executable and its runfiles.",
        "runtime_modules": "List of ZigModuleInfo modules imported by generated translate-c output.",
    },
)

def _disable_translate_c_transition_impl(_, __):
    return {
        "//zig/settings:translate_c": False,
    }

_disable_translate_c_transition = transition(
    implementation = _disable_translate_c_transition_impl,
    inputs = [],
    outputs = [
        "//zig/settings:translate_c",
    ],
)

def _translate_c_toolchain_impl(ctx):
    translate_c = ctx.attr.translate_c[0] if type(ctx.attr.translate_c) == "list" else ctx.attr.translate_c
    translatectoolchaininfo = TranslateCToolchainInfo(
        executable = ctx.executable.translate_c,
        files_to_run = translate_c[DefaultInfo].files_to_run,
        runtime_modules = [dep[ZigModuleInfo] for dep in ctx.attr.runtime_modules],
    )
    return [
        platform_common.ToolchainInfo(
            translatectoolchaininfo = translatectoolchaininfo,
        ),
    ]

translate_c_toolchain = rule(
    implementation = _translate_c_toolchain_impl,
    attrs = {
        "translate_c": attr.label(
            doc = "The translate-c executable target or prebuilt executable file.",
            allow_files = True,
            cfg = _disable_translate_c_transition,
            executable = True,
            mandatory = True,
        ),
        "runtime_modules": attr.label_list(
            doc = "Zig modules imported by Zig code generated by the translate-c executable.",
            cfg = _disable_translate_c_transition,
            providers = [ZigModuleInfo],
        ),
    },
    doc = "Defines a translate-c toolchain.",
)
