"""Rules to declare translate-c toolchains."""

load(
    "//zig/private/providers:zig_module_info.bzl",
    "zig_module_info",
)

TranslateCToolchainInfo = provider(
    doc = "Information about how to invoke an external translate-c executable.",
    fields = {
        "executable": "File, The translate-c executable.",
        "runtime_modules": "List of translate-c runtime modules imported by generated translate-c output.",
        "runfiles": "Depset of files required to run the translate-c executable.",
    },
)

TranslateCRuntimeModuleInfo = provider(
    doc = "Information about a Zig runtime module imported by generated translate-c output.",
    fields = {
        "canonical_name": "String, The canonical Zig module name.",
        "main": "File, The main Zig source file.",
        "name": "String, The Zig import name.",
    },
)

def _disable_translate_c_transition_impl(_, __):
    return {
        "//zig/settings:translate_c": False,
    }

_disable_translate_c_transition = transition(
    implementation = _disable_translate_c_transition_impl,
    inputs = [],
    outputs = [
        "//zig/settings:translate_c",
    ],
)

def _translate_c_toolchain_impl(ctx):
    translate_c = ctx.attr.translate_c[0] if type(ctx.attr.translate_c) == "list" else ctx.attr.translate_c
    default_info = translate_c[DefaultInfo]
    executable = default_info.files_to_run.executable
    if not executable:
        fail("translate_c must provide an executable")
    translatectoolchaininfo = TranslateCToolchainInfo(
        executable = executable,
        runtime_modules = [dep[TranslateCRuntimeModuleInfo] for dep in ctx.attr.runtime_modules],
        runfiles = default_info.default_runfiles.files,
    )
    return [
        platform_common.ToolchainInfo(
            translatectoolchaininfo = translatectoolchaininfo,
        ),
    ]

translate_c_toolchain = rule(
    implementation = _translate_c_toolchain_impl,
    attrs = {
        "translate_c": attr.label(
            doc = "The translate-c executable target.",
            mandatory = True,
            cfg = _disable_translate_c_transition,
        ),
        "runtime_modules": attr.label_list(
            doc = "Zig modules imported by Zig code generated by the translate-c executable.",
            cfg = _disable_translate_c_transition,
            providers = [TranslateCRuntimeModuleInfo],
        ),
    },
    doc = "Defines a translate-c toolchain.",
)

def _translate_c_runtime_module_impl(ctx):
    import_name = ctx.attr.import_name or ctx.label.name
    canonical_name = ctx.attr.canonical_name or import_name
    return [
        DefaultInfo(files = depset([ctx.file.main])),
        TranslateCRuntimeModuleInfo(
            canonical_name = canonical_name,
            main = ctx.file.main,
            name = import_name,
        ),
        zig_module_info(
            name = import_name,
            canonical_name = canonical_name,
            main = ctx.file.main,
        ),
    ]

translate_c_runtime_module = rule(
    implementation = _translate_c_runtime_module_impl,
    attrs = {
        "canonical_name": attr.string(
            doc = "Optional canonical Zig module name. Defaults to the import name.",
        ),
        "import_name": attr.string(
            doc = "Name used by generated translate-c Zig code to import this module. Defaults to the target name.",
        ),
        "main": attr.label(
            allow_single_file = [".zig"],
            doc = "The main Zig source file for this runtime module.",
            mandatory = True,
        ),
    },
    doc = "Declares a Zig runtime module imported by output generated from translate-c.",
)
