load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_zig//zig:defs.bzl", "zig_binary", "zig_module", "zig_shared_library", "zig_static_library")

cc_library(
    name = "indirect",
    srcs = ["indirect.c"],
    hdrs = ["indirect.h"],
    visibility = ["//zig/tests:__pkg__"],
)

zig_module(
    name = "direct",
    main = "direct.zig",
    visibility = ["//zig/tests:__pkg__"],
    deps = [":indirect"],
)

zig_shared_library(
    name = "shared_library",
    main = "main.zig",
    visibility = ["//zig/tests:__pkg__"],
    deps = [":direct"],
)

zig_static_library(
    name = "static_library",
    main = "main.zig",
    visibility = ["//zig/tests:__pkg__"],
    deps = [":direct"],
)

zig_binary(
    name = "binary",
    main = "main.zig",
    visibility = ["//zig/tests:__pkg__"],
    deps = [":direct"],
)
